import React from 'react'
import Head from 'next/head'
const About = () => {
    return (<>
        <Head>
            <title>Huntiing Coder About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div>
                This is About Page
            </div>
        </main>
    </>
    )
}

export default About
